sudo: true
language: haskell

cache:
  directories:
    - "$HOME/.stack"
    - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    curl -sSL https://get.haskellstack.org/ | sh

    stack --version
    stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - |
    stack test --system-ghc

