name:                symbiotic
version:             0.0.0
github:              "symbiotic-data/symbiotic-haskell"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2019 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Interoperable data types
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/symbiotic-data/symbiotic-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- cereal
- containers
- text
- time
- unfoldable
- unordered-containers
- vector

library:
  source-dirs: src
  generated-exposed-modules:
  - Paths_symbiotic
  exposed-modules:
    - Data.Symbiotic.Primitives.Unit
    - Data.Symbiotic.Primitives.Boolean
    - Data.Symbiotic.Primitives.Floating.Float32.BE
    - Data.Symbiotic.Primitives.Floating.Float32.LE
    - Data.Symbiotic.Primitives.Floating.Float64.BE
    - Data.Symbiotic.Primitives.Floating.Float64.LE
    - Data.Symbiotic.Primitives.Integral.Int16.BE
    - Data.Symbiotic.Primitives.Integral.Int16.LE
    - Data.Symbiotic.Primitives.Integral.Int32.BE
    - Data.Symbiotic.Primitives.Integral.Int32.LE
    - Data.Symbiotic.Primitives.Integral.Int64.BE
    - Data.Symbiotic.Primitives.Integral.Int64.LE
    - Data.Symbiotic.Primitives.Integral.Uint16.BE
    - Data.Symbiotic.Primitives.Integral.Uint16.LE
    - Data.Symbiotic.Primitives.Integral.Uint32.BE
    - Data.Symbiotic.Primitives.Integral.Uint32.LE
    - Data.Symbiotic.Primitives.Integral.Uint64.BE
    - Data.Symbiotic.Primitives.Integral.Uint64.LE
    - Data.Symbiotic.Primitives.Integral.Integer8
    - Data.Symbiotic.Primitives.Integral.Integer16
    - Data.Symbiotic.Primitives.Integral.Integer32
    - Data.Symbiotic.Primitives.Integral.Integer64
    - Data.Symbiotic.Primitives.Integral.Natural8
    - Data.Symbiotic.Primitives.Integral.Natural16
    - Data.Symbiotic.Primitives.Integral.Natural32
    - Data.Symbiotic.Primitives.Integral.Natural64
    - Data.Symbiotic.Primitives.UTF8Strings.String8
    - Data.Symbiotic.Primitives.UTF8Strings.String16
    - Data.Symbiotic.Primitives.UTF8Strings.String32
    - Data.Symbiotic.Primitives.UTF8Strings.String64
    - Data.Symbiotic.PrimitiveComposites.Collections.Vector8
    - Data.Symbiotic.PrimitiveComposites.Collections.Vector16
    - Data.Symbiotic.PrimitiveComposites.Collections.Vector32
    - Data.Symbiotic.PrimitiveComposites.Collections.Vector64
    - Data.Symbiotic.PrimitiveComposites.Either
    - Data.Symbiotic.SophisticatedComposites.Mappings.StringMap8
    - Data.Symbiotic.SophisticatedComposites.Mappings.StringMap16
    - Data.Symbiotic.SophisticatedComposites.Mappings.StringMap32
    - Data.Symbiotic.SophisticatedComposites.Mappings.StringMap64
    - Data.Symbiotic.SophisticatedComposites.Mappings.Map8
    - Data.Symbiotic.SophisticatedComposites.Mappings.Map16
    - Data.Symbiotic.SophisticatedComposites.Mappings.Map32
    - Data.Symbiotic.SophisticatedComposites.Mappings.Map64
    - Data.Symbiotic.Casual.Chronological.Date

tests:
  symbiotic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symbiotic
